package(default_visibility = ["//:__subpackages__"])

exports_files([
    "python_rules.bzl",
    "run_shell.bzl",
    "deps.bzl",
])

filegroup(
    name = "_pytest_wrapper",
    srcs = ["_pytest_wrapper.py"],
)
