#!/usr/bin/env bash

set -euo pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "$GIT_ROOT" || exit 1

# Running buildifier on all BUILD files
bazel run //:buildifier

# Running python formatter
black .
isort .
