#!/usr/bin/env bash

set -euo pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "$GIT_ROOT" || exit 1

# Running buildifier on all BUILD files
bazel run //:buildifier -- -lint fix

# Running python formatter check
black --check .
isort --check .
